/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Audio: typeof import('./src/components/player/audio.vue')['default']
    Audiocontext: typeof import('./src/components/player/audiocontext.vue')['default']
    Container: typeof import('./src/components/container/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElText: typeof import('element-plus/es')['ElText']
    Fullscreen: typeof import('./src/components/layout/fullscreen/index.vue')['default']
    Header: typeof import('./src/components/layout/header.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    MenuTree: typeof import('./src/components/layout/sidebar/menu-tree.vue')['default']
    OnlineTable: typeof import('./src/components/onlineTable/index.vue')['default']
    PageTransition: typeof import('./src/components/layout/page-transition/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/sidebar/sidebar.vue')['default']
    Useinfo: typeof import('./src/components/layout/useinfo/index.vue')['default']
    UserList: typeof import('./src/components/userList/index.vue')['default']
    Video: typeof import('./src/components/player/video.vue')['default']
  }
}
